# Generated by Django 2.2.4 on 2019-09-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledatatype',
            name='module_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
