# Generated by Django 2.2.4 on 2019-09-19 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testweb', '0002_auto_20190918_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledatatype',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testweb.ModuleDataType', verbose_name='自关联'),
        ),
    ]
