# Generated by Django 2.2.4 on 2019-09-19 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testweb', '0003_moduledatatype_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduledatatype',
            old_name='pid',
            new_name='classes',
        ),
    ]
