# Generated by Django 2.2.4 on 2019-09-19 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testweb', '0004_auto_20190919_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledatatype',
            name='classes',
        ),
        migrations.CreateModel(
            name='ModuleStruct',
            fields=[
                ('struct_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('struct_name', models.CharField(max_length=16)),
                ('struct_type', models.CharField(max_length=8)),
                ('struct_sort', models.IntegerField(default=0)),
                ('struct_content', models.CharField(max_length=32)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testweb.ModuleDataType')),
            ],
            options={
                'db_table': 'ModuleStruct',
            },
        ),
    ]
