# Generated by Django 2.2.4 on 2019-09-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testweb', '0005_auto_20190919_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledatatype',
            name='des',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='modulestruct',
            name='struct_sort',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modulestruct',
            name='struct_type',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
